CC      = arm-linux-gnueabihf-gcc-4.9
CXX     = arm-linux-gnueabihf-g++-4.9
CFLAGS  = -g -O3 -Wall -std=c++0x -pthread -I.
LIBS    = -lpthread
LDFLAGS = -g

OBJECTS = \
		network/UDPSocket.o \
		edac/SHA256.o \
		RemoteCommand.o

all:	dvmcmd

dvmcmd: $(OBJECTS) 
		$(CXX) $(OBJECTS) $(CFLAGS) $(LIBS) -o dvmcmd

%.o: %.cpp
		$(CXX) $(CFLAGS) -c -o $@ $<

clean:
		$(RM) dvmcmd *.o *.d *.bak *~ network/*.o edac/*.o
